# Generated by Django 3.2.7 on 2021-09-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0002_rename_description_snack_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='purchaser',
            new_name='author',
        ),
    ]
